{% set name = "ansiwrap" %}
{% set version = "0.8.4" %}
{% set bundle = "zip" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: ca0c740734cde59bf919f8ff2c386f74f9a369818cdc60efe94893d01ea8d9b7
  patches:
    - py312.patch

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - textwrap3

test:
  requires:
    - python {{ python_min }}
  imports:
    - ansiwrap

about:
  home: https://github.com/jonathaneunice/ansiwrap
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: textwrap, but savvy to ANSI colors and styles
  description: 'ansiwrap wraps text, like the standard textwrap module. But it also correctly wraps text that contains ANSI control sequences that colorize or style text.'
  dev_url: https://github.com/jonathaneunice/ansiwrap

extra:
  recipe-maintainers:
    - pmlandwehr
